version: "3"
services:
  isc-dhcp-api:
    image: ghcr.io/spacerouter/isc-dhcp-api:latest
    container_name: isc-dhcp-api
    environment:
      DHCPD_LEASES: '/var/lib/dhcp/dhcpd.leases'
      DHCPD_CONF: '/etc/dhcp/dhcpd.conf'
    networks:
     - traefik-public
    volumes:
      - "/etc/sr/dhcp/data/var:/var/lib/dhcp/"
      - "/etc/sr/dhcp/data/etc:/etc/dhcp/"
    labels:
      traefik.http.services.dhcp.loadbalancer.server.port: '8080'
      traefik.http.routers.dhcp.rule: (Host(`api.opengate.lan`) && PathPrefix(`/dhcp`))
      traefik.http.routers.dhcp.entrypoints: web
      traefik.enable: 'true'
      traefik.http.routers.dhcp.service: dhcp
    restart: always
networks:
  traefik-public:
    external: true
