version: '3'
services:
  dhcp:
    build: .
    container_name: isc-dhcp-server
    network_mode: "host"
    image: isc-dhcp-server
    ports:
      - "67:67/udp"
    volumes:
      - ./data/dhcp:/data/dhcp
    restart: always
