version: "3"
services:
  dhcp:
    image: ghcr.io/spacerouter/isc-dhcp-server:latest
    container_name: isc-dhcp-server
    network_mode: "host"
    volumes:
      - "/etc/sr/dhcp/data/var:/var/lib/dhcp/"
      - "/etc/sr/dhcp/data/etc:/etc/dhcp/"
    restart: always
