version: '3'
services:
  dhcp:
    build: .
    container_name: isc-dhcp-server
    network_mode: "host"
    image: isc-dhcp-server
    ports:
      - "67:67/udp"
    volumes:
      - "../dhcp/var:/var/lib/dhcp/"
      - "../dhcp/etc:/etc/dhcp"
    restart: always
